# prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000'] # 'backend' is the Docker Compose service name, 3000 is its exposed port
        labels:
          application: 'ezMedSafe-Backend'

  - job_name: 'neo4j-browser' # Optional: Monitor Neo4j browser/HTTP interface
    static_configs:
      - targets: ['neo4j:7474']
        labels:
          application: 'Neo4j-Browser'